# Generated by Django 2.1.7 on 2021-04-03 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0005_auto_20210403_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedLeaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaves_taken', models.DecimalField(decimal_places=1, max_digits=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavefrom', models.DateField()),
                ('leavetill', models.DateField()),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('applied_date', models.DateField(default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True, null=True)),
                ('first_approver_status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=12, null=True)),
                ('second_approver_status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=12, null=True)),
                ('third_approver_status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=12, null=True)),
                ('first_approver_remark', models.TextField(blank=True, null=True)),
                ('second_approver_remark', models.TextField(blank=True, null=True)),
                ('third_approver_remark', models.TextField(blank=True, null=True)),
                ('leave_state', models.CharField(default='Pending', max_length=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeavesAllottedTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('total_leaves', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('year', models.CharField(max_length=9)),
                ('maximum_leaves', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='leavesallottedtotal',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.LeaveType'),
        ),
        migrations.AddField(
            model_name='approvedleaves',
            name='leaverequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.LeaveRequest'),
        ),
        migrations.AddField(
            model_name='approvedleaves',
            name='leavetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.LeaveType'),
        ),
    ]
