# Generated by Django 2.1.7 on 2021-04-06 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leaveapproverlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapproverlist',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='leaveapproverlist',
            name='request',
        ),
        migrations.DeleteModel(
            name='LeaveApproverList',
        ),
    ]
