# Generated by Django 2.1.7 on 2021-04-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20210406_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='can_apply',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=3),
            preserve_default=False,
        ),
    ]
