# Generated by Django 2.1.7 on 2021-04-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leavetype_can_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='code',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
    ]
