# Generated by Django 2.1.7 on 2021-04-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_leavetype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_sick',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
            preserve_default=False,
        ),
    ]
