# Generated by Django 2.1.7 on 2021-05-22 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('med', '0002_auto_20210519_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=60)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='DietOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='KitchenUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
                ('active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120)),
                ('mrno', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('age', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ptcreatedusers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ptupdatedusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='visit',
            name='age',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='mrno',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='dietorder',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='med.ItemCategory'),
        ),
        migrations.AddField(
            model_name='dietorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dtcreatedusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='med.DietItem'),
        ),
        migrations.AddField(
            model_name='dietorder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='med.Visit'),
        ),
        migrations.AddField(
            model_name='dietorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dtupdatedusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietitem',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='med.ItemCategory'),
        ),
        migrations.AddField(
            model_name='dietitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='med.KitchenUnit'),
        ),
        migrations.AddField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='med.Patient'),
            preserve_default=False,
        ),
    ]
