# Generated by Django 2.1.7 on 2021-05-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_auto_20210522_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='med.Department')),
            ],
        ),
        migrations.AddField(
            model_name='dietorder',
            name='special_instruction',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='med.Doctor'),
            preserve_default=False,
        ),
    ]
