# Generated by Django 2.1.7 on 2021-05-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_auto_20210523_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name='dietitem',
            old_name='unit',
            new_name='kitchen_unit',
        ),
        migrations.AddField(
            model_name='dietitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dietorder',
            name='slot',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Special', 'Special')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='default_unit_value',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='measurement_unit',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='med.MeasurementUnit'),
            preserve_default=False,
        ),
    ]
