# Generated by Django 2.1.7 on 2021-05-31 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0006_auto_20210527_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietorder',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='measurement',
            field=models.CharField(choices=[('Milligram', 'Milligram'), ('Gram', 'Gram'), ('Kilogram', 'Kilogram'), ('Milliliter', 'Milliliter'), ('Liter', 'Liter'), ('Bowl-Small', 'Bowl-Small'), ('Bowl-Medium', 'Bowl-Medium'), ('Bowl-Large', 'Bowl-Large')], max_length=20),
        ),
    ]
