# Generated by Django 2.1.7 on 2021-06-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0007_auto_20210531_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='ipno',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
