# Generated by Django 2.1.7 on 2021-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devicelogs42021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicelogid', models.IntegerField(db_column='DeviceLogId')),
                ('downloaddate', models.DateTimeField(blank=True, db_column='DownloadDate', null=True)),
                ('deviceid', models.IntegerField(blank=True, db_column='DeviceId', null=True)),
                ('userid', models.CharField(blank=True, db_column='UserId', max_length=50, null=True)),
                ('logdate', models.DateTimeField(blank=True, db_column='LogDate', null=True)),
                ('direction', models.CharField(blank=True, db_column='Direction', max_length=100, null=True)),
                ('attdirection', models.CharField(blank=True, db_column='AttDirection', max_length=255, null=True)),
                ('c1', models.CharField(blank=True, db_column='C1', max_length=255, null=True)),
                ('c2', models.CharField(blank=True, db_column='C2', max_length=255, null=True)),
                ('c3', models.CharField(blank=True, db_column='C3', max_length=255, null=True)),
                ('c4', models.CharField(blank=True, db_column='C4', max_length=255, null=True)),
                ('c5', models.CharField(blank=True, db_column='C5', max_length=255, null=True)),
                ('c6', models.CharField(blank=True, db_column='C6', max_length=255, null=True)),
                ('c7', models.CharField(blank=True, db_column='C7', max_length=255, null=True)),
                ('workcode', models.CharField(blank=True, db_column='WorkCode', max_length=100, null=True)),
                ('updateflag', models.IntegerField(blank=True, db_column='UpdateFlag', null=True)),
                ('isapproved', models.IntegerField(blank=True, db_column='IsApproved', null=True)),
                ('employeeimage', models.TextField(blank=True, db_column='EmployeeImage', null=True)),
                ('filename', models.CharField(blank=True, db_column='FileName', max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, db_column='Longitude', max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, db_column='Latitude', max_length=255, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('lastmodifieddate', models.DateTimeField(blank=True, db_column='LastModifiedDate', null=True)),
                ('locationaddress', models.CharField(blank=True, db_column='LocationAddress', max_length=4000, null=True)),
                ('bodytemperature', models.FloatField(blank=True, db_column='BodyTemperature', null=True)),
                ('ismaskon', models.IntegerField(blank=True, db_column='IsMaskOn', null=True)),
            ],
            options={
                'db_table': 'DeviceLogs_4_2021',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins', models.CharField(max_length=20)),
            ],
        ),
    ]
