# Generated by Django 2.1.7 on 2021-05-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eattendance', '0002_auto_20210506_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insta',
            new_name='Ins',
        ),
    ]
