# Generated by Django 2.1.7 on 2021-05-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eattendance', '0003_auto_20210506_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devicelogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicelogid', models.IntegerField()),
                ('downloaddate', models.DateTimeField(blank=True, null=True)),
                ('deviceid', models.IntegerField(blank=True, null=True)),
                ('userid', models.CharField(blank=True, max_length=50, null=True)),
                ('logdate', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=100, null=True)),
                ('attdirection', models.CharField(blank=True, max_length=255, null=True)),
                ('c1', models.CharField(blank=True, max_length=255, null=True)),
                ('c2', models.CharField(blank=True, max_length=255, null=True)),
                ('c3', models.CharField(blank=True, max_length=255, null=True)),
                ('c4', models.CharField(blank=True, max_length=255, null=True)),
                ('c5', models.CharField(blank=True, max_length=255, null=True)),
                ('c6', models.CharField(blank=True, max_length=255, null=True)),
                ('c7', models.CharField(blank=True, max_length=255, null=True)),
                ('workcode', models.CharField(blank=True, max_length=100, null=True)),
                ('updateflag', models.IntegerField(blank=True, null=True)),
                ('isapproved', models.IntegerField(blank=True, null=True)),
                ('employeeimage', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('lastmodifieddate', models.DateTimeField(blank=True, null=True)),
                ('locationaddress', models.CharField(blank=True, max_length=4000, null=True)),
                ('bodytemperature', models.FloatField(blank=True, null=True)),
                ('is_maskon', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
