# Generated by Django 2.1.7 on 2021-05-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eattendance', '0004_devicelogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelogs',
            name='id',
        ),
        migrations.AlterField(
            model_name='devicelogs',
            name='devicelogid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
