# Generated by Django 2.1.7 on 2021-05-07 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_auto_20210405_1010'),
        ('eattendance', '0005_auto_20210507_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField(null=True)),
                ('out_time', models.DateTimeField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('holiday', models.DateField()),
                ('desciption', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_date', models.DateField(null=True)),
                ('is_weekend', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('shift_from', models.TimeField(blank=True, null=True)),
                ('shift_to', models.TimeField(blank=True, null=True)),
                ('shift_margin', models.BooleanField(choices=[(True, 'Enable'), (False, 'Disable')])),
                ('margin_before', models.TimeField(blank=True, null=True)),
                ('margin_after', models.TimeField(blank=True, null=True)),
                ('shift_type', models.CharField(choices=[('Flexible-day', 'Flexible(Day)'), ('Flexible-night', 'Flexible(Night)'), ('fixed-shift-time', 'Fixed Shift Time')], max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='roster',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eattendance.Shift'),
        ),
    ]
