# Generated by Django 2.1.7 on 2021-05-13 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eattendance', '0008_auto_20210512_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updatedadusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='roster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updatedrosterusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cbdausers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdrosterusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
