# Generated by Django 2.1.7 on 2021-04-02 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20210402_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employee.State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employee.Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='registration_details',
            field=models.TextField(),
        ),
    ]
