# Generated by Django 2.1.7 on 2021-04-02 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_auto_20210402_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApprover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='desc',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaveapprover',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='Employee.Department'),
        ),
        migrations.AddField(
            model_name='leaveapprover',
            name='leave_approver1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_approvers', to='Employee.Employee'),
        ),
        migrations.AddField(
            model_name='leaveapprover',
            name='leave_approver2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_approvers', to='Employee.Employee'),
        ),
        migrations.AddField(
            model_name='leaveapprover',
            name='leave_approver3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_approvers', to='Employee.Employee'),
        ),
    ]
