# Generated by Django 2.1.7 on 2021-04-03 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_auto_20210402_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='rank',
            new_name='leave_approve_level_depth',
        ),
    ]
