# Generated by Django 2.1.7 on 2021-04-05 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_auto_20210403_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapprover',
            name='leave_approver1',
        ),
        migrations.RemoveField(
            model_name='leaveapprover',
            name='leave_approver2',
        ),
        migrations.RemoveField(
            model_name='leaveapprover',
            name='leave_approver3',
        ),
        migrations.AddField(
            model_name='leaveapprover',
            name='approver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='Employee.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaveapprover',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapprover',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depatments', to='Employee.Department'),
        ),
    ]
