# Generated by Django 2.1.7 on 2021-05-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Employee'), (3, 'Manager'), (4, 'Hod'), (5, 'Administraive Officer'), (6, 'CAO')], primary_key=True, serialize=False),
        ),
    ]
