# Generated by Django 2.1.7 on 2021-05-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210501_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Employee'), (2, 'Supervisor'), (3, 'Manager'), (4, 'HR Executive'), (5, 'Hod'), (6, 'HR Head'), (7, 'Administraive Officer'), (8, 'CAO')], primary_key=True, serialize=False),
        ),
    ]
